version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Tests
          command: yarn test --reporters="default" --reporters="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/results.xml
      - store_test_results:
          path: test-results
